"""Task service for business logic operations."""

from datetime import datetime
from typing import Optional
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.models.task import Task, TaskCreate, TaskUpdate


class TaskService:
    """Service class for task-related business logic."""

    def __init__(self, session: AsyncSession):
        """Initialize the task service with a database session."""
        self.session = session

    async def create_task(self, user_id: str, data: TaskCreate) -> Task:
        """Create a new task for the specified user.

        Args:
            user_id: The ID of the user creating the task
            data: Task creation data (title, optional description)

        Returns:
            The created Task object

        Raises:
            ValueError: If title is empty or exceeds 200 characters
        """
        # Validate title
        if not data.title or not data.title.strip():
            raise ValueError("Task title cannot be empty")
        if len(data.title) > 200:
            raise ValueError("Task title cannot exceed 200 characters")

        task = Task(
            user_id=user_id,  # The id will be auto-generated by the model
            title=data.title.strip(),
            description=data.description.strip() if data.description else None,
            completed=False,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        )

        self.session.add(task)
        await self.session.commit()
        await self.session.refresh(task)

        return task

    async def list_tasks(self, user_id: str) -> list[Task]:
        """Get all tasks for the specified user.

        Args:
            user_id: The ID of the user

        Returns:
            List of Task objects belonging to the user, ordered by creation date (newest first)
        """
        result = await self.session.execute(
            select(Task)
            .where(Task.user_id == user_id)
            .order_by(Task.created_at.desc())
        )
        return list(result.scalars().all())

    async def get_task(self, user_id: str, task_id: str) -> Optional[Task]:
        """Get a specific task by ID.

        Args:
            user_id: The ID of the user (for ownership verification)
            task_id: The ID of the task

        Returns:
            The Task object if found and owned by user, None otherwise
        """
        result = await self.session.execute(
            select(Task)
            .where(Task.id == task_id)
            .where(Task.user_id == user_id)
        )
        return result.scalar_one_or_none()

    async def update_task(
        self, user_id: str, task_id: str, data: TaskUpdate
    ) -> Optional[Task]:
        """Update an existing task.

        Args:
            user_id: The ID of the user (for ownership verification)
            task_id: The ID of the task to update
            data: Update data (title and/or description)

        Returns:
            The updated Task object if found, None otherwise

        Raises:
            ValueError: If title is empty or exceeds 200 characters
        """
        task = await self.get_task(user_id, task_id)
        if not task:
            return None

        # Validate and update title if provided
        if data.title is not None:
            if not data.title.strip():
                raise ValueError("Task title cannot be empty")
            if len(data.title) > 200:
                raise ValueError("Task title cannot exceed 200 characters")
            task.title = data.title.strip()

        # Update description if provided
        if data.description is not None:
            task.description = data.description.strip() if data.description else None

        task.updated_at = datetime.utcnow()

        await self.session.commit()
        await self.session.refresh(task)

        return task

    async def delete_task(self, user_id: str, task_id: str) -> bool:
        """Delete a task.

        Args:
            user_id: The ID of the user (for ownership verification)
            task_id: The ID of the task to delete

        Returns:
            True if deleted, False if not found or not owned by user
        """
        task = await self.get_task(user_id, task_id)
        if not task:
            return False

        await self.session.delete(task)
        await self.session.commit()

        return True

    async def toggle_complete(self, user_id: str, task_id: str) -> Optional[Task]:
        """Toggle the completion status of a task.

        Args:
            user_id: The ID of the user (for ownership verification)
            task_id: The ID of the task

        Returns:
            The updated Task object if found, None otherwise
        """
        task = await self.get_task(user_id, task_id)
        if not task:
            return None

        task.completed = not task.completed
        task.updated_at = datetime.utcnow()

        await self.session.commit()
        await self.session.refresh(task)

        return task
