apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-bot.fullname" . }}-secret
  labels:
    {{- include "todo-bot.labels" . | nindent 4 }}
type: Opaque
data:
  better-auth-secret: {{ .Values.backend.env.BETTER_AUTH_SECRET | b64enc | quote }}